# Generated by Django 5.1.7 on 2025-03-24 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('balance_amount', models.FloatField(default=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.FloatField()),
                ('interest_rate', models.IntegerField(default=6)),
                ('loan_period', models.IntegerField()),
                ('total_amount', models.FloatField(default=0)),
                ('monthly_emi', models.FloatField(default=0)),
                ('no_of_emis', models.IntegerField(default=0)),
                ('paid_amount', models.FloatField(default=0)),
                ('loan_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_amount', models.FloatField()),
                ('transaction_type', models.CharField(choices=[('LEND', 'LEND'), ('LUMPSUM', 'LUMPSUM'), ('EMI', 'EMI')], default='EMI', max_length=10)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.loan')),
            ],
        ),
    ]
