# Generated by Django 5.1.7 on 2025-03-24 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_paid_amount_loan_remaining_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='customer',
        ),
    ]
